# Generated by Django 3.2.6 on 2024-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apoderado', models.CharField(max_length=300)),
                ('edad_apoderado', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=100)),
                ('num_documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('apoderados', models.CharField(max_length=550)),
                ('terms_cond', models.CharField(max_length=40)),
                ('firma_imagen', models.BinaryField(blank=True, null=True)),
                ('hashcode', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
