# Generated by Django 3.2.6 on 2024-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrymodel',
            name='firma_imagen',
            field=models.CharField(max_length=40),
        ),
    ]
