# Generated by Django 3.2.6 on 2024-12-16 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_modeloregistro_firma_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloregistro',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modeloregistro',
            name='firma_imagen',
            field=models.CharField(max_length=12000),
        ),
    ]
